name: CD
on:
  - push

jobs:
  ubuntu:
    name: Ubuntu (Launchpad)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch the entire history so we can create the changelog

    - name: Package for Launchpad
      id: package
      uses: ./.github/actions/package-launchpad
      with:
        DEB_PASSPHRASE: ${{ secrets.DEB_PASSPHRASE }}
        DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}

    - name: Deploy to Launchpad
      uses: ./.github/actions/deploy-launchpad
      with:
        changes_files: ${{ steps.package.outputs.changes_files }}
        devel-repo: "ppa:texworks/ppa"
        stable-repo: "ppa:texworks/stable"

################################################################################

  macosx-bintray:
    name: Mac OS X (Bintray)
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        # Temporary fix for https://github.com/actions/virtual-environments/issues/1811
        brew untap local/homebrew-openssl
        brew untap local/homebrew-python2
        # End of fix
        brew update > brew_update.log || { echo "::error::Updating homebrew failed"; cat brew_update.log; exit 1; }
        brew install hunspell poppler lua qt5

    - name: Configure
      run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"

    - name: Build
      run: make -j
      working-directory: build

    - name: Test
      run: QT_QPA_PLATFORM_PLUGIN_PATH="${Qt5_DIR}/plugins/platforms" ctest -V
      working-directory: build

    - name: Package
      id: package
      uses: ./.github/actions/package-macos

    - name: Deploy to Bintray
      uses: ./.github/actions/deploy-bintray
      with:
        file: build/${{ steps.package.outputs.file }}
        subject: texworks
        repo: OSX-latest
        pkg: TeXworks-for-Mac:latest
        version: ${{ steps.package.outputs.version }}
        username: stloeffler
        key: ${{ secrets.bintray_key }}
